apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: http-dump
      labels:
        app: http-dump
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: http-dump
      template:
        metadata:
          labels:
            app: http-dump
        spec:
          containers:
          - name: http-dump
            image: scalify/http-dump
            ports:
            - name: http
              containerPort: 8080
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
              limits:
                cpu: 100m
                memory: 100Mi
            livenessProbe:
              httpGet:
                path: /
                port: http
            readinessProbe:
              httpGet:
                path: /
                port: http
  - apiVersion: v1
    kind: Service
    metadata:
      name: http-dump
      labels:
        app: http-dump
    spec:
      type: NodePort
      selector:
        app: http-dump
      ports:
        - protocol: TCP
          port: 80
          targetPort: http
